
package com.example.demo.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataComSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataComSoap {


    /**
     * 
     * @param webservicePwd
     * @param schoolID
     * @param userBarcode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ClearUserInfo", action = "http://tempuri.org/ClearUserInfo")
    @WebResult(name = "ClearUserInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ClearUserInfo", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.ClearUserInfo")
    @ResponseWrapper(localName = "ClearUserInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.ClearUserInfoResponse")
    public String clearUserInfo(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "UserBarcode", targetNamespace = "http://tempuri.org/")
        String userBarcode);

    /**
     * 
     * @param webservicePwd
     * @param schoolID
     * @param userBarcode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DownloadUserInfo", action = "http://tempuri.org/DownloadUserInfo")
    @WebResult(name = "DownloadUserInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DownloadUserInfo", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.DownloadUserInfo")
    @ResponseWrapper(localName = "DownloadUserInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.DownloadUserInfoResponse")
    public String downloadUserInfo(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "UserBarcode", targetNamespace = "http://tempuri.org/")
        String userBarcode);

    /**
     * 
     * @param webservicePwd
     * @param itemLocationNum
     * @param schoolID
     * @param itemBarcode
     * @param itemRFID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateItemInfo", action = "http://tempuri.org/UpdateItemInfo")
    @WebResult(name = "UpdateItemInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateItemInfo", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.UpdateItemInfo")
    @ResponseWrapper(localName = "UpdateItemInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.UpdateItemInfoResponse")
    public String updateItemInfo(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "ItemBarcode", targetNamespace = "http://tempuri.org/")
        String itemBarcode,
        @WebParam(name = "ItemRFID", targetNamespace = "http://tempuri.org/")
        String itemRFID,
        @WebParam(name = "ItemLocationNum", targetNamespace = "http://tempuri.org/")
        String itemLocationNum);

    /**
     * 
     * @param webservicePwd
     * @param userRFID
     * @param schoolID
     * @param userBarcode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateUserInfo", action = "http://tempuri.org/UpdateUserInfo")
    @WebResult(name = "UpdateUserInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateUserInfo", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.UpdateUserInfo")
    @ResponseWrapper(localName = "UpdateUserInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.UpdateUserInfoResponse")
    public String updateUserInfo(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "UserBarcode", targetNamespace = "http://tempuri.org/")
        String userBarcode,
        @WebParam(name = "UserRFID", targetNamespace = "http://tempuri.org/")
        String userRFID);

    /**
     * 
     * @param webservicePwd
     * @param userRightGroup
     * @param userRFID
     * @param userExpiryDate
     * @param schoolID
     * @param userDepartment
     * @param userBarcode
     * @param userRegDate
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateNewUser", action = "http://tempuri.org/CreateNewUser")
    @WebResult(name = "CreateNewUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateNewUser", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.CreateNewUser")
    @ResponseWrapper(localName = "CreateNewUserResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.CreateNewUserResponse")
    public String createNewUser(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "UserDepartment", targetNamespace = "http://tempuri.org/")
        String userDepartment,
        @WebParam(name = "UserBarcode", targetNamespace = "http://tempuri.org/")
        String userBarcode,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "UserRFID", targetNamespace = "http://tempuri.org/")
        String userRFID,
        @WebParam(name = "UserRightGroup", targetNamespace = "http://tempuri.org/")
        String userRightGroup,
        @WebParam(name = "UserRegDate", targetNamespace = "http://tempuri.org/")
        String userRegDate,
        @WebParam(name = "UserExpiryDate", targetNamespace = "http://tempuri.org/")
        String userExpiryDate);

    /**
     * 
     * @param webservicePwd
     * @param schoolID
     * @param department
     * @param superiorDepartment
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateNewDepartment", action = "http://tempuri.org/CreateNewDepartment")
    @WebResult(name = "CreateNewDepartmentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateNewDepartment", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.CreateNewDepartment")
    @ResponseWrapper(localName = "CreateNewDepartmentResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.CreateNewDepartmentResponse")
    public String createNewDepartment(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "Department", targetNamespace = "http://tempuri.org/")
        String department,
        @WebParam(name = "SuperiorDepartment", targetNamespace = "http://tempuri.org/")
        String superiorDepartment);

    /**
     * 
     * @param webservicePwd
     * @param itemID
     * @param schoolID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetItemInfo", action = "http://tempuri.org/GetItemInfo")
    @WebResult(name = "GetItemInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItemInfo", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemInfo")
    @ResponseWrapper(localName = "GetItemInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemInfoResponse")
    public String getItemInfo(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "ItemID", targetNamespace = "http://tempuri.org/")
        String itemID);

    /**
     * 
     * @param webservicePwd
     * @param itemlocationnum
     * @param schoolID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetItemInfoByLocation", action = "http://tempuri.org/GetItemInfoByLocation")
    @WebResult(name = "GetItemInfoByLocationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItemInfoByLocation", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemInfoByLocation")
    @ResponseWrapper(localName = "GetItemInfoByLocationResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemInfoByLocationResponse")
    public String getItemInfoByLocation(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "Itemlocationnum", targetNamespace = "http://tempuri.org/")
        String itemlocationnum);

    /**
     * 
     * @param webservicePwd
     * @param endDate
     * @param schoolID
     * @param userID
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUserBorrowRecords", action = "http://tempuri.org/GetUserBorrowRecords")
    @WebResult(name = "GetUserBorrowRecordsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUserBorrowRecords", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetUserBorrowRecords")
    @ResponseWrapper(localName = "GetUserBorrowRecordsResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetUserBorrowRecordsResponse")
    public String getUserBorrowRecords(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        String userID,
        @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 
     * @param webservicePwd
     * @param endDate
     * @param schoolID
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetALLBorrowRecords", action = "http://tempuri.org/GetALLBorrowRecords")
    @WebResult(name = "GetALLBorrowRecordsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetALLBorrowRecords", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetALLBorrowRecords")
    @ResponseWrapper(localName = "GetALLBorrowRecordsResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetALLBorrowRecordsResponse")
    public String getALLBorrowRecords(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 
     * @param webservicePwd
     * @param endDate
     * @param schoolID
     * @param userID
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUserReadDuration", action = "http://tempuri.org/GetUserReadDuration")
    @WebResult(name = "GetUserReadDurationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUserReadDuration", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetUserReadDuration")
    @ResponseWrapper(localName = "GetUserReadDurationResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetUserReadDurationResponse")
    public String getUserReadDuration(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        String userID,
        @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 
     * @param webservicePwd
     * @param startStorageDate
     * @param schoolID
     * @param endStorageDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetItemInfoByDate", action = "http://tempuri.org/GetItemInfoByDate")
    @WebResult(name = "GetItemInfoByDateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItemInfoByDate", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemInfoByDate")
    @ResponseWrapper(localName = "GetItemInfoByDateResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemInfoByDateResponse")
    public String getItemInfoByDate(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "StartStorageDate", targetNamespace = "http://tempuri.org/")
        String startStorageDate,
        @WebParam(name = "EndStorageDate", targetNamespace = "http://tempuri.org/")
        String endStorageDate);

    /**
     * 
     * @param webservicePwd
     * @param itemName
     * @param schoolID
     * @param itemClassFication
     * @param itemCallNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetItemInfoByKeywords", action = "http://tempuri.org/GetItemInfoByKeywords")
    @WebResult(name = "GetItemInfoByKeywordsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItemInfoByKeywords", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemInfoByKeywords")
    @ResponseWrapper(localName = "GetItemInfoByKeywordsResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemInfoByKeywordsResponse")
    public String getItemInfoByKeywords(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "ItemName", targetNamespace = "http://tempuri.org/")
        String itemName,
        @WebParam(name = "ItemClassFication", targetNamespace = "http://tempuri.org/")
        String itemClassFication,
        @WebParam(name = "ItemCallNumber", targetNamespace = "http://tempuri.org/")
        String itemCallNumber);

    /**
     * 
     * @param webservicePwd
     * @param itemType
     * @param topX
     * @param endDate
     * @param schoolID
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBookBorrowTopX", action = "http://tempuri.org/GetBookBorrowTopX")
    @WebResult(name = "GetBookBorrowTopXResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBookBorrowTopX", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetBookBorrowTopX")
    @ResponseWrapper(localName = "GetBookBorrowTopXResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetBookBorrowTopXResponse")
    public String getBookBorrowTopX(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "ItemType", targetNamespace = "http://tempuri.org/")
        String itemType,
        @WebParam(name = "TopX", targetNamespace = "http://tempuri.org/")
        String topX,
        @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 
     * @param webservicePwd
     * @param endDate
     * @param schoolID
     * @param itemKeywords
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetItemBorrowRecords", action = "http://tempuri.org/GetItemBorrowRecords")
    @WebResult(name = "GetItemBorrowRecordsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItemBorrowRecords", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemBorrowRecords")
    @ResponseWrapper(localName = "GetItemBorrowRecordsResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemBorrowRecordsResponse")
    public String getItemBorrowRecords(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "ItemKeywords", targetNamespace = "http://tempuri.org/")
        String itemKeywords,
        @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 
     * @param webservicePwd
     * @param itemType
     * @param topX
     * @param endDate
     * @param schoolID
     * @param userDepartment
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUserBorrowTopX", action = "http://tempuri.org/GetUserBorrowTopX")
    @WebResult(name = "GetUserBorrowTopXResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUserBorrowTopX", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetUserBorrowTopX")
    @ResponseWrapper(localName = "GetUserBorrowTopXResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetUserBorrowTopXResponse")
    public String getUserBorrowTopX(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "ItemType", targetNamespace = "http://tempuri.org/")
        String itemType,
        @WebParam(name = "UserDepartment", targetNamespace = "http://tempuri.org/")
        String userDepartment,
        @WebParam(name = "TopX", targetNamespace = "http://tempuri.org/")
        String topX,
        @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
        String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 
     * @param webservicePwd
     * @param pageNumber
     * @param author
     * @param schoolID
     * @param isbn
     * @param publisher
     * @param numPerPage
     * @param title
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetItemInfoByKeywordsPaging", action = "http://tempuri.org/GetItemInfoByKeywordsPaging")
    @WebResult(name = "GetItemInfoByKeywordsPagingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItemInfoByKeywordsPaging", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemInfoByKeywordsPaging")
    @ResponseWrapper(localName = "GetItemInfoByKeywordsPagingResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemInfoByKeywordsPagingResponse")
    public String getItemInfoByKeywordsPaging(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "Title", targetNamespace = "http://tempuri.org/")
        String title,
        @WebParam(name = "Author", targetNamespace = "http://tempuri.org/")
        String author,
        @WebParam(name = "Publisher", targetNamespace = "http://tempuri.org/")
        String publisher,
        @WebParam(name = "ISBN", targetNamespace = "http://tempuri.org/")
        String isbn,
        @WebParam(name = "NumPerPage", targetNamespace = "http://tempuri.org/")
        String numPerPage,
        @WebParam(name = "PageNumber", targetNamespace = "http://tempuri.org/")
        String pageNumber);

    /**
     * 
     * @param webservicePwd
     * @param pageNumber
     * @param schoolID
     * @param batchNum
     * @param numPerPage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetItemInfoByBatchNumPaging", action = "http://tempuri.org/GetItemInfoByBatchNumPaging")
    @WebResult(name = "GetItemInfoByBatchNumPagingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItemInfoByBatchNumPaging", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemInfoByBatchNumPaging")
    @ResponseWrapper(localName = "GetItemInfoByBatchNumPagingResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemInfoByBatchNumPagingResponse")
    public String getItemInfoByBatchNumPaging(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "BatchNum", targetNamespace = "http://tempuri.org/")
        String batchNum,
        @WebParam(name = "NumPerPage", targetNamespace = "http://tempuri.org/")
        String numPerPage,
        @WebParam(name = "PageNumber", targetNamespace = "http://tempuri.org/")
        String pageNumber);

    /**
     * 
     * @param webservicePwd
     * @param pageNumber
     * @param schoolID
     * @param oneKeyword
     * @param numPerPage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetItemInfoByOneKeywordPaging", action = "http://tempuri.org/GetItemInfoByOneKeywordPaging")
    @WebResult(name = "GetItemInfoByOneKeywordPagingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItemInfoByOneKeywordPaging", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemInfoByOneKeywordPaging")
    @ResponseWrapper(localName = "GetItemInfoByOneKeywordPagingResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemInfoByOneKeywordPagingResponse")
    public String getItemInfoByOneKeywordPaging(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "OneKeyword", targetNamespace = "http://tempuri.org/")
        String oneKeyword,
        @WebParam(name = "NumPerPage", targetNamespace = "http://tempuri.org/")
        String numPerPage,
        @WebParam(name = "PageNumber", targetNamespace = "http://tempuri.org/")
        String pageNumber);

    /**
     * 
     * @param webservicePwd
     * @param schoolID
     * @param oneKeyword
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetItemNumByOneKeyword", action = "http://tempuri.org/GetItemNumByOneKeyword")
    @WebResult(name = "GetItemNumByOneKeywordResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItemNumByOneKeyword", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemNumByOneKeyword")
    @ResponseWrapper(localName = "GetItemNumByOneKeywordResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemNumByOneKeywordResponse")
    public String getItemNumByOneKeyword(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "OneKeyword", targetNamespace = "http://tempuri.org/")
        String oneKeyword);

    /**
     * 
     * @param webservicePwd
     * @param author
     * @param schoolID
     * @param publisher
     * @param title
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetItemNumByKeywords", action = "http://tempuri.org/GetItemNumByKeywords")
    @WebResult(name = "GetItemNumByKeywordsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItemNumByKeywords", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemNumByKeywords")
    @ResponseWrapper(localName = "GetItemNumByKeywordsResponse", targetNamespace = "http://tempuri.org/", className = "com.example.demo.webservice.GetItemNumByKeywordsResponse")
    public String getItemNumByKeywords(
        @WebParam(name = "SchoolID", targetNamespace = "http://tempuri.org/")
        String schoolID,
        @WebParam(name = "WebservicePwd", targetNamespace = "http://tempuri.org/")
        String webservicePwd,
        @WebParam(name = "Title", targetNamespace = "http://tempuri.org/")
        String title,
        @WebParam(name = "Author", targetNamespace = "http://tempuri.org/")
        String author,
        @WebParam(name = "Publisher", targetNamespace = "http://tempuri.org/")
        String publisher);

}
