
package com.example.demo.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataCom", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://139.224.235.152/DataCom.asmx?wsdl")
public class DataCom
    extends Service
{

    private final static URL DATACOM_WSDL_LOCATION;
    private final static WebServiceException DATACOM_EXCEPTION;
    private final static QName DATACOM_QNAME = new QName("http://tempuri.org/", "DataCom");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://139.224.235.152/DataCom.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATACOM_WSDL_LOCATION = url;
        DATACOM_EXCEPTION = e;
    }

    public DataCom() {
        super(__getWsdlLocation(), DATACOM_QNAME);
    }

    public DataCom(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATACOM_QNAME, features);
    }

    public DataCom(URL wsdlLocation) {
        super(wsdlLocation, DATACOM_QNAME);
    }

    public DataCom(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATACOM_QNAME, features);
    }

    public DataCom(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataCom(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataComSoap
     */
    @WebEndpoint(name = "DataComSoap")
    public DataComSoap getDataComSoap() {
        return super.getPort(new QName("http://tempuri.org/", "DataComSoap"), DataComSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataComSoap
     */
    @WebEndpoint(name = "DataComSoap")
    public DataComSoap getDataComSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "DataComSoap"), DataComSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns DataComSoap
     */
    @WebEndpoint(name = "DataComSoap12")
    public DataComSoap getDataComSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "DataComSoap12"), DataComSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataComSoap
     */
    @WebEndpoint(name = "DataComSoap12")
    public DataComSoap getDataComSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "DataComSoap12"), DataComSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATACOM_EXCEPTION!= null) {
            throw DATACOM_EXCEPTION;
        }
        return DATACOM_WSDL_LOCATION;
    }

}
